# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K8stool < Formula
  desc "A command-line tool for managing Kubernetes resources"
  homepage "https://github.com/eniayomi/k8stool"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eniayomi/k8stool/releases/download/v0.1.1/k8stool_Darwin_x86_64.tar.gz"
      sha256 "b51cbd1a8a795f3f9154012a532a4ebc9faf0ae74a7c4927f450c1c4f92bf224"

      def install
        bin.install "k8stool"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eniayomi/k8stool/releases/download/v0.1.1/k8stool_Darwin_arm64.tar.gz"
      sha256 "be80d6b6c5593b24bdaadc44bb998d7082396e04403ad8f1198c445fe757938c"

      def install
        bin.install "k8stool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/eniayomi/k8stool/releases/download/v0.1.1/k8stool_Linux_x86_64.tar.gz"
        sha256 "bba5fd4b7395b1f103500335f824f99cf4aa3299ee8b8fbcfaa36f48547a5fc7"

        def install
          bin.install "k8stool"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/eniayomi/k8stool/releases/download/v0.1.1/k8stool_Linux_arm64.tar.gz"
        sha256 "0d31f2f61638a2c3edb12d349dcf2ed9f6800109489ef9a86936595e1953a8cf"

        def install
          bin.install "k8stool"
        end
      end
    end
  end

  test do
    system "#{bin}/k8stool version"
  end
end
