# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K8stool < Formula
  desc "A command-line tool for managing Kubernetes resources"
  homepage "https://github.com/eniayomi/k8stool"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eniayomi/k8stool/releases/download/v0.0.5/k8stool_Darwin_x86_64.tar.gz"
      sha256 "08d99a6cf4b5a9d254d36e6ae66b25e5307ffeccfa4c05729935abfc983ed50b"

      def install
        bin.install "k8stool"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eniayomi/k8stool/releases/download/v0.0.5/k8stool_Darwin_arm64.tar.gz"
      sha256 "25109f9975cceee94d763ccd0dbb268d14decf8d17507439d7513430701ae519"

      def install
        bin.install "k8stool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/eniayomi/k8stool/releases/download/v0.0.5/k8stool_Linux_x86_64.tar.gz"
        sha256 "b3a7f3ae910986cb5ad73b24991d8353ef1df279a813886d006a09028d9f056c"

        def install
          bin.install "k8stool"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/eniayomi/k8stool/releases/download/v0.0.5/k8stool_Linux_arm64.tar.gz"
        sha256 "073891e2385e0dcd9a2895da574ff336fe867b06188430d4a917c95ba7c1089f"

        def install
          bin.install "k8stool"
        end
      end
    end
  end

  test do
    system "#{bin}/k8stool version"
  end
end
